### ISSUE TITLE
请问忘记后台admin密码如何重置？

### ISSUE THREAD

**Issue by xulianggg** [mizhexiaoxiao/WebsiteGuide#11]

**Comment by mizhexiaoxiao** [comment]
1. 把db.sqlite3拷贝出来 
`docker cp websiteguide:/WebsiteGuide/db.sqlite3 . `
2. 找个数据库编辑器打开db.sqlite3，表websiteapp_userinfo，admin的password字段值修改为
`pbkdf2_sha256$150000$l8yRqOYqKCFq$Bm3BalPJWV3ez2sG0PYjpBlHZi765hHtzH8b1lr+k/k=`
3. 把db.sqlite3拷贝回去
`docker cp db.sqlite3 websiteguide:/WebsiteGuide/db.sqlite3`
4. 打开后台输入账号`admin`密码`admin@1234`即可登录

之前没有预留忘记密码功能，可以用上面的方式临时解决。

**Comment by xulianggg** [comment]
好的，谢谢佬

**Comment by xulianggg** [comment]
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/50935979/219604031-c80969f3-5c02-4be8-9024-f8f9f0c5c5ad.png">
大佬，我改了，还是不行。还有别的办法吗？

**Comment by mizhexiaoxiao** [comment]
有执行第三步吗

**Comment by xulianggg** [comment]
我是用docker-compose起的容器，db文件在本地，我本地修改完之后还重启了容器，但是登录还是提示密码错误

**Comment by mizhexiaoxiao** [comment]
执行这条命令创建一个用户，账号`user`密码`admin@1234`，进去后台再重置admin密码也可以
`docker exec -it websiteguide python /WebsiteGuide/manage.py useradd -u user -p admin@1234 -s -n 用户`

**Comment by xulianggg** [comment]
感谢大佬，可以了。
