### ISSUE TITLE
静态文件位置没设置好，dist压根就没有~~~    

### ISSUE THREAD

**Issue by 1021581800** [mizhexiaoxiao/WebsiteGuide#5]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [os.path.join(BASE_DIR, 'templates')]
        'DIRS': [os.path.join(BASE_DIR, 'websitefronted/dist')]       #《《《《《《《《this

**Comment by mizhexiaoxiao** [comment]
dist需要打包后生成，且当成django静态文件处理时才生效，目前静态文件由NGINX处理，这里的设置可忽略
